export const GET_NEWS_DATA = "GET_NEWS_DATA";
export const GET_NEWS_DATA_SUCCESS = "GET_NEWS_DATA_SUCCESS";
export const GET_NEWS_DATA_FAIL = "GET_NEWS_DATA_FAIL";
export const GET_AUTOMOTIVE_DATA = "GET_AUTOMOTIVE_DATA";
export const GET_AUTOMOTIVE_DATA_SUCCESS = "GET_AUTOMOTIVE_DATA_SUCCESS";
export const GET_AUTOMOTIVE_DATA_FAIL = "GET_AUTOMOTIVE_DATA_FAIL";